version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydatabase
    volumes:
      - ./on-prem-service-setup/db-postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  
  app:
    build:
      dockerfile: ./api/Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: mydatabase
    ports:
      - "8000:80"
    depends_on:
      - db